
-- =============================================================
-- Org Chart Migration: employee_details + org_structure_details
-- Employees: 115, Roots: 6
-- =============================================================


INSERT INTO org_members (id, org_id, parent_id, name, title, dept, region, level, headcount, sort_order) VALUES ('1656', 1, '0', 'Thor', 'CEO', 'CEO', 'NA', 'C', 1, 1);
INSERT INTO org_members (id, org_id, parent_id, name, title, dept, region, level, headcount, sort_order) VALUES ('1657', 1, '1656', 'James Bond', 'COO', 'COO', 'NA', 'Direct', 9, 2);
INSERT INTO org_members (id, org_id, parent_id, name, title, dept, region, level, headcount, sort_order) VALUES ('1658', 1, '1657', 'Robert Downey', 'Chief Financial Officer', 'Finance', 'NA', 'VP', 2, 3);
INSERT INTO org_members (id, org_id, parent_id, name, title, dept, region, level, headcount, sort_order) VALUES ('1659', 1, '1657', 'Halle Berry', 'Chief Technology Officer', 'Technology', 'Africa', 'VP', 0, 4);
INSERT INTO org_members (id, org_id, parent_id, name, title, dept, region, level, headcount, sort_order) VALUES ('1660', 1, '1657', 'Employee 1660', 'Staff', 'General', 'NA', 'VP', 0, 5);
INSERT INTO org_members (id, org_id, parent_id, name, title, dept, region, level, headcount, sort_order) VALUES ('1661', 1, '1657', 'Hemsworth', 'CSO', 'Sales', 'NA', 'VP', 14, 6);
INSERT INTO org_members (id, org_id, parent_id, name, title, dept, region, level, headcount, sort_order) VALUES ('1662', 1, '1658', 'KENNY', 'Budget Planner', 'Finance', 'NA', 'Director', 7, 7);
INSERT INTO org_members (id, org_id, parent_id, name, title, dept, region, level, headcount, sort_order) VALUES ('1663', 1, '1658', 'HEIDI', 'Accounting', 'Finance', 'NA', 'Director', 3, 8);
INSERT INTO org_members (id, org_id, parent_id, name, title, dept, region, level, headcount, sort_order) VALUES ('1664', 1, '1661', 'JOHN', 'Sales - America', 'Sales', 'NA', 'Director', 0, 9);
INSERT INTO org_members (id, org_id, parent_id, name, title, dept, region, level, headcount, sort_order) VALUES ('1665', 1, '1661', 'TOM', 'Sales - UK', 'Sales', 'NA', 'Director', 2, 10);
INSERT INTO org_members (id, org_id, parent_id, name, title, dept, region, level, headcount, sort_order) VALUES ('1666', 1, '1661', 'Employee 1666', 'Staff', 'General', 'NA', 'Director', 1, 11);
INSERT INTO org_members (id, org_id, parent_id, name, title, dept, region, level, headcount, sort_order) VALUES ('1667', 1, '1668', 'Kevin', 'Staff', 'Sales', 'NA', 'Director', 1, 12);
INSERT INTO org_members (id, org_id, parent_id, name, title, dept, region, level, headcount, sort_order) VALUES ('1668', 1, '1657', 'Jennifer Lawrence', 'CMO', 'Marketing', 'NA', 'VP', 4, 13);
INSERT INTO org_members (id, org_id, parent_id, name, title, dept, region, level, headcount, sort_order) VALUES ('1676', 1, '1667', 'Roger', 'Staff', 'General', 'NA', 'Lead', 0, 14);
INSERT INTO org_members (id, org_id, parent_id, name, title, dept, region, level, headcount, sort_order) VALUES ('1684', 1, '1666', 'Employee 1684', 'Staff', 'General', 'NA', 'Lead', 0, 15);
INSERT INTO org_members (id, org_id, parent_id, name, title, dept, region, level, headcount, sort_order) VALUES ('1685', 1, '1668', 'Taker', 'CMO', 'Marketing', 'NA', 'Director', 1, 16);
INSERT INTO org_members (id, org_id, parent_id, name, title, dept, region, level, headcount, sort_order) VALUES ('1686', 1, '1662', 'Employee 1686', 'Staff', 'General', 'NA', 'Lead', 0, 17);
INSERT INTO org_members (id, org_id, parent_id, name, title, dept, region, level, headcount, sort_order) VALUES ('1687', 1, '1661', 'Employee 1687', 'Staff', 'General', 'NA', 'Director', 0, 18);
INSERT INTO org_members (id, org_id, parent_id, name, title, dept, region, level, headcount, sort_order) VALUES ('1688', 1, '1661', 'ace', 'CSO-SALES', 'General', 'NA', 'Director', 0, 19);
INSERT INTO org_members (id, org_id, parent_id, name, title, dept, region, level, headcount, sort_order) VALUES ('1689', 1, '1661', 'acf', 'CSO-SALES', 'General', 'NA', 'Director', 1, 20);
INSERT INTO org_members (id, org_id, parent_id, name, title, dept, region, level, headcount, sort_order) VALUES ('1690', 1, '1661', 'ach', 'CSO-SALES', 'General', 'NA', 'Director', 1, 21);
INSERT INTO org_members (id, org_id, parent_id, name, title, dept, region, level, headcount, sort_order) VALUES ('1691', 1, '1661', 'acj', 'CSO-SALES', 'General', 'NA', 'Director', 0, 22);
INSERT INTO org_members (id, org_id, parent_id, name, title, dept, region, level, headcount, sort_order) VALUES ('1692', 1, '1661', 'Employee 1692', 'Staff', 'General', 'NA', 'Director', 0, 23);
INSERT INTO org_members (id, org_id, parent_id, name, title, dept, region, level, headcount, sort_order) VALUES ('1693', 1, '1661', 'acl', 'CSO-SALES', 'General', 'NA', 'Director', 0, 24);
INSERT INTO org_members (id, org_id, parent_id, name, title, dept, region, level, headcount, sort_order) VALUES ('1694', 1, '1661', 'aco', 'CSO-SALES', 'General', 'NA', 'Director', 0, 25);
INSERT INTO org_members (id, org_id, parent_id, name, title, dept, region, level, headcount, sort_order) VALUES ('1695', 1, '1661', 'Employee 1695', 'Staff', 'General', 'NA', 'Director', 0, 26);
INSERT INTO org_members (id, org_id, parent_id, name, title, dept, region, level, headcount, sort_order) VALUES ('1696', 1, '1661', 'acy', 'CSO-SALES', 'General', 'NA', 'Director', 0, 27);
INSERT INTO org_members (id, org_id, parent_id, name, title, dept, region, level, headcount, sort_order) VALUES ('1697', 1, '1665', 'Adam', 'Sales', 'Sales', 'NA', 'Lead', 3, 28);
INSERT INTO org_members (id, org_id, parent_id, name, title, dept, region, level, headcount, sort_order) VALUES ('1698', 1, '1697', 'Mary', 'Officer', 'General', 'NA', 'Lead', 1, 29);
INSERT INTO org_members (id, org_id, parent_id, name, title, dept, region, level, headcount, sort_order) VALUES ('1699', 1, '1698', 'Employee 1699', 'Staff', 'General', 'NA', 'Lead', 0, 30);
INSERT INTO org_members (id, org_id, parent_id, name, title, dept, region, level, headcount, sort_order) VALUES ('1700', 1, '1689', 'Employee 1700', 'Staff', 'General', 'NA', 'Lead', 1, 31);
INSERT INTO org_members (id, org_id, parent_id, name, title, dept, region, level, headcount, sort_order) VALUES ('1701', 1, '1700', 'Employee 1701', 'Staff', 'General', 'NA', 'Lead', 0, 32);
INSERT INTO org_members (id, org_id, parent_id, name, title, dept, region, level, headcount, sort_order) VALUES ('1702', 1, '1690', 'Employee 1702', 'Staff', 'General', 'NA', 'Lead', 1, 33);
INSERT INTO org_members (id, org_id, parent_id, name, title, dept, region, level, headcount, sort_order) VALUES ('1703', 1, '1702', 'Employee 1703', 'Staff', 'General', 'NA', 'Lead', 0, 34);
INSERT INTO org_members (id, org_id, parent_id, name, title, dept, region, level, headcount, sort_order) VALUES ('1704', 1, '1663', 'Employee 1704', 'Staff', 'General', 'NA', 'Lead', 0, 35);
INSERT INTO org_members (id, org_id, parent_id, name, title, dept, region, level, headcount, sort_order) VALUES ('1705', 1, '1663', 'Employee 1705', 'Staff', 'General', 'NA', 'Lead', 0, 36);
INSERT INTO org_members (id, org_id, parent_id, name, title, dept, region, level, headcount, sort_order) VALUES ('1709', 1, '1744', 'red', 'GHJ', 'General', 'NA', 'Director', 0, 37);
INSERT INTO org_members (id, org_id, parent_id, name, title, dept, region, level, headcount, sort_order) VALUES ('1710', 1, '1744', 'Tester 1', 'DFG', 'General', 'NA', 'Director', 0, 38);
INSERT INTO org_members (id, org_id, parent_id, name, title, dept, region, level, headcount, sort_order) VALUES ('1711', 1, '1663', 'tets', 'ss', 'ssss', 'ch', 'Lead', 0, 39);
INSERT INTO org_members (id, org_id, parent_id, name, title, dept, region, level, headcount, sort_order) VALUES ('1712', 1, '1697', 'test2', 'Staff', 'General', 'NA', 'Lead', 0, 40);
INSERT INTO org_members (id, org_id, parent_id, name, title, dept, region, level, headcount, sort_order) VALUES ('1713', 1, '1661', 'Divine', 'Sales - UK', 'Sales', 'NA', 'Director', 0, 41);
INSERT INTO org_members (id, org_id, parent_id, name, title, dept, region, level, headcount, sort_order) VALUES ('1717', 1, '1697', 'raj', 'ss', 'sample', 'NA', 'Lead', 0, 42);
INSERT INTO org_members (id, org_id, parent_id, name, title, dept, region, level, headcount, sort_order) VALUES ('1718', 1, '1668', 'testeer', 'CMO', 'Marketing', 'NA', 'Director', 0, 43);
INSERT INTO org_members (id, org_id, parent_id, name, title, dept, region, level, headcount, sort_order) VALUES ('1722', 1, '1685', 'nrsd', 'dd', 'sample', 'NA', 'Lead', 0, 44);
INSERT INTO org_members (id, org_id, parent_id, name, title, dept, region, level, headcount, sort_order) VALUES ('1734', 1, '1657', 'Mike', 'Staff', 'General', 'NA', 'VP', 5, 45);
INSERT INTO org_members (id, org_id, parent_id, name, title, dept, region, level, headcount, sort_order) VALUES ('1735', 1, '1734', 'Rodan', 'Staff', 'General', 'NA', 'Director', 0, 46);
INSERT INTO org_members (id, org_id, parent_id, name, title, dept, region, level, headcount, sort_order) VALUES ('1736', 1, '1734', 'Violet', 'Staff', 'General', 'NA', 'Director', 0, 47);
INSERT INTO org_members (id, org_id, parent_id, name, title, dept, region, level, headcount, sort_order) VALUES ('1737', 1, '1734', 'Nike', 'Staff', 'General', 'NA', 'Director', 0, 48);
INSERT INTO org_members (id, org_id, parent_id, name, title, dept, region, level, headcount, sort_order) VALUES ('1740', 1, '1734', 'Kavipriya', 'Staff', 'General', 'NA', 'Director', 3, 49);
INSERT INTO org_members (id, org_id, parent_id, name, title, dept, region, level, headcount, sort_order) VALUES ('1741', 1, '1740', 'Employee 1741', 'Staff', 'General', 'NA', 'Lead', 0, 50);
INSERT INTO org_members (id, org_id, parent_id, name, title, dept, region, level, headcount, sort_order) VALUES ('1742', 1, '1740', 'Employee 1742', 'Staff', 'General', 'NA', 'Lead', 0, 51);
INSERT INTO org_members (id, org_id, parent_id, name, title, dept, region, level, headcount, sort_order) VALUES ('1743', 1, '1668', 'Rocket', 'CMO', 'Marketing', 'NA', 'Director', 0, 52);
INSERT INTO org_members (id, org_id, parent_id, name, title, dept, region, level, headcount, sort_order) VALUES ('1744', 1, '1657', 'Employee 1744', 'Staff', 'General', 'NA', 'VP', 4, 53);
INSERT INTO org_members (id, org_id, parent_id, name, title, dept, region, level, headcount, sort_order) VALUES ('1745', 1, '1740', 'Kavipriya', 'Staff', 'General', 'NA', 'Lead', 0, 54);
INSERT INTO org_members (id, org_id, parent_id, name, title, dept, region, level, headcount, sort_order) VALUES ('1746', 1, '1744', 'Tester 2', 'ASD', 'General', 'NA', 'Director', 1, 55);
INSERT INTO org_members (id, org_id, parent_id, name, title, dept, region, level, headcount, sort_order) VALUES ('1747', 1, '1744', 'Green', 'GHJ', 'General', 'NA', 'Director', 0, 56);
INSERT INTO org_members (id, org_id, parent_id, name, title, dept, region, level, headcount, sort_order) VALUES ('1749', 1, '1746', 'suresh', 'admin asst', 'ADMIN', 'NA', 'Lead', 0, 57);
INSERT INTO org_members (id, org_id, parent_id, name, title, dept, region, level, headcount, sort_order) VALUES ('1755', 1, '1657', 'Rakesh', 'Staff', 'General', 'NA', 'VP', 3, 58);
INSERT INTO org_members (id, org_id, parent_id, name, title, dept, region, level, headcount, sort_order) VALUES ('1756', 1, '1755', 'Neon', 'Staff', 'General', 'NA', 'Director', 0, 59);
INSERT INTO org_members (id, org_id, parent_id, name, title, dept, region, level, headcount, sort_order) VALUES ('1757', 1, '1657', 'Rohit', 'Staff', 'General', 'NA', 'VP', 0, 60);
INSERT INTO org_members (id, org_id, parent_id, name, title, dept, region, level, headcount, sort_order) VALUES ('1758', 1, '1755', 'Gayle', 'Staff', 'General', 'NA', 'Director', 0, 61);
INSERT INTO org_members (id, org_id, parent_id, name, title, dept, region, level, headcount, sort_order) VALUES ('1759', 1, '1755', 'Arjun', 'Staff', 'General', 'NA', 'Director', 0, 62);
INSERT INTO org_members (id, org_id, parent_id, name, title, dept, region, level, headcount, sort_order) VALUES ('1760', 1, '1734', 'Niranjan', 'Staff', 'General', 'NA', 'Director', 0, 63);
INSERT INTO org_members (id, org_id, parent_id, name, title, dept, region, level, headcount, sort_order) VALUES ('1766', 1, '0', 'Dhoni', 'CEO', 'CEO1', 'NA', 'C', 2, 64);
INSERT INTO org_members (id, org_id, parent_id, name, title, dept, region, level, headcount, sort_order) VALUES ('1767', 1, '1766', 'Raina', 'CS', 'CS_2', 'NA', 'Direct', 10, 65);
INSERT INTO org_members (id, org_id, parent_id, name, title, dept, region, level, headcount, sort_order) VALUES ('1768', 1, '1767', 'Virat', 'Admin', 'Ad1', 'NA', 'VP', 1, 66);
INSERT INTO org_members (id, org_id, parent_id, name, title, dept, region, level, headcount, sort_order) VALUES ('1769', 1, '1767', 'Ashwin', 'CF', 'CF_2', 'NA', 'VP', 3, 67);
INSERT INTO org_members (id, org_id, parent_id, name, title, dept, region, level, headcount, sort_order) VALUES ('1770', 1, '1769', 'Employee 1770', 'Staff', 'General', 'NA', 'Director', 1, 68);
INSERT INTO org_members (id, org_id, parent_id, name, title, dept, region, level, headcount, sort_order) VALUES ('1771', 1, '1769', 'Rahul', 'Staff', 'General', 'NA', 'Director', 1, 69);
INSERT INTO org_members (id, org_id, parent_id, name, title, dept, region, level, headcount, sort_order) VALUES ('1772', 1, '1768', 'Sanju', 'Staff', 'SPR', 'NA', 'Director', 2, 70);
INSERT INTO org_members (id, org_id, parent_id, name, title, dept, region, level, headcount, sort_order) VALUES ('1773', 1, '1769', 'Hardik', 'IT', 'IT', 'NA', 'Director', 1, 71);
INSERT INTO org_members (id, org_id, parent_id, name, title, dept, region, level, headcount, sort_order) VALUES ('1774', 1, '1810', 'Dinesh', 'Staff', 'General', 'NA', 'VP', 0, 72);
INSERT INTO org_members (id, org_id, parent_id, name, title, dept, region, level, headcount, sort_order) VALUES ('1775', 1, '1772', 'Bumrah', 'Staff', 'General', 'NA', 'Lead', 0, 73);
INSERT INTO org_members (id, org_id, parent_id, name, title, dept, region, level, headcount, sort_order) VALUES ('1776', 1, '1773', 'Deepak raj', 'Staff', 'General', 'NA', 'Lead', 0, 74);
INSERT INTO org_members (id, org_id, parent_id, name, title, dept, region, level, headcount, sort_order) VALUES ('1777', 1, '1772', 'Jadeja', 'Staff', 'General', 'NA', 'Lead', 1, 75);
INSERT INTO org_members (id, org_id, parent_id, name, title, dept, region, level, headcount, sort_order) VALUES ('1778', 1, '1777', 'Yadav', 'Staff', 'General', 'NA', 'Lead', 1, 76);
INSERT INTO org_members (id, org_id, parent_id, name, title, dept, region, level, headcount, sort_order) VALUES ('1779', 1, '1778', 'Jadhav', 'Staff', 'General', 'NA', 'Lead', 2, 77);
INSERT INTO org_members (id, org_id, parent_id, name, title, dept, region, level, headcount, sort_order) VALUES ('1780', 1, '1779', 'Dravid', 'Staff', 'CTT', 'NA', 'Lead', 0, 78);
INSERT INTO org_members (id, org_id, parent_id, name, title, dept, region, level, headcount, sort_order) VALUES ('1781', 1, '1779', 'Employee 1781', 'Staff', 'General', 'NA', 'Lead', 0, 79);
INSERT INTO org_members (id, org_id, parent_id, name, title, dept, region, level, headcount, sort_order) VALUES ('1782', 1, '1770', 'Tendulkar', 'Staff', 'General', 'NA', 'Lead', 1, 80);
INSERT INTO org_members (id, org_id, parent_id, name, title, dept, region, level, headcount, sort_order) VALUES ('1783', 1, '1782', 'Sharma', 'Staff', 'General', 'NA', 'Lead', 0, 81);
INSERT INTO org_members (id, org_id, parent_id, name, title, dept, region, level, headcount, sort_order) VALUES ('1797', 1, '1771', 'mini', 'Staff', 'General', 'NA', 'Lead', 0, 82);
INSERT INTO org_members (id, org_id, parent_id, name, title, dept, region, level, headcount, sort_order) VALUES ('1799', 1, '1767', 'Warner', 'Staff', 'General', 'NA', 'VP', 2, 83);
INSERT INTO org_members (id, org_id, parent_id, name, title, dept, region, level, headcount, sort_order) VALUES ('1800', 1, '1767', 'Karthik', 'IT', 'IT', 'NA', 'VP', 1, 84);
INSERT INTO org_members (id, org_id, parent_id, name, title, dept, region, level, headcount, sort_order) VALUES ('1802', 1, '1799', 'Roger', 'Staff', 'General', 'NA', 'Director', 0, 85);
INSERT INTO org_members (id, org_id, parent_id, name, title, dept, region, level, headcount, sort_order) VALUES ('1803', 1, '1767', 'Jadejha', 'Staff', 'General', 'NA', 'VP', 0, 86);
INSERT INTO org_members (id, org_id, parent_id, name, title, dept, region, level, headcount, sort_order) VALUES ('1804', 1, '1767', 'Bieber', 'Staff', 'General', 'NA', 'VP', 1, 87);
INSERT INTO org_members (id, org_id, parent_id, name, title, dept, region, level, headcount, sort_order) VALUES ('1805', 1, '1800', 'newre', 'Staff', 'General', 'NA', 'Director', 0, 88);
INSERT INTO org_members (id, org_id, parent_id, name, title, dept, region, level, headcount, sort_order) VALUES ('1806', 1, '1665', 'sssresr', 'Staff', 'General', 'NA', 'Lead', 0, 89);
INSERT INTO org_members (id, org_id, parent_id, name, title, dept, region, level, headcount, sort_order) VALUES ('1807', 1, '1804', 'Goulding', 'Staff', 'General', 'NA', 'Director', 0, 90);
INSERT INTO org_members (id, org_id, parent_id, name, title, dept, region, level, headcount, sort_order) VALUES ('1810', 1, '1766', 'Sachin', 'Staff', 'General', 'NA', 'Direct', 1, 91);
INSERT INTO org_members (id, org_id, parent_id, name, title, dept, region, level, headcount, sort_order) VALUES ('1881', 1, '1767', 'Niranjan', 'sales', 'S_1', 'NA', 'VP', 7, 92);
INSERT INTO org_members (id, org_id, parent_id, name, title, dept, region, level, headcount, sort_order) VALUES ('1882', 1, '1881', 'vijay', 'sales', 's4', 'NA', 'Director', 0, 93);
INSERT INTO org_members (id, org_id, parent_id, name, title, dept, region, level, headcount, sort_order) VALUES ('1883', 1, '1881', 'vijay', 'sales', 'General', 'NA', 'Director', 0, 94);
INSERT INTO org_members (id, org_id, parent_id, name, title, dept, region, level, headcount, sort_order) VALUES ('1884', 1, '1881', 'selva', 'sales', 'a3', 'NA', 'Director', 0, 95);
INSERT INTO org_members (id, org_id, parent_id, name, title, dept, region, level, headcount, sort_order) VALUES ('1885', 1, '1881', 'Jagan', 'Pre-sales', 'PS_01', 'NA', 'Director', 1, 96);
INSERT INTO org_members (id, org_id, parent_id, name, title, dept, region, level, headcount, sort_order) VALUES ('1886', 1, '1881', 'nivetha', 'auditing', 'A-06', 'NA', 'Director', 0, 97);
INSERT INTO org_members (id, org_id, parent_id, name, title, dept, region, level, headcount, sort_order) VALUES ('1887', 1, '1767', 'praveen', 'qc', 'q_01', 'NA', 'VP', 0, 98);
INSERT INTO org_members (id, org_id, parent_id, name, title, dept, region, level, headcount, sort_order) VALUES ('1888', 1, '1767', 'avyukth', 'qc', 'q_07', 'NA', 'VP', 0, 99);
INSERT INTO org_members (id, org_id, parent_id, name, title, dept, region, level, headcount, sort_order) VALUES ('1889', 1, '1885', 'yuvan', 'qc', 'q4', 'NA', 'Lead', 0, 100);
INSERT INTO org_members (id, org_id, parent_id, name, title, dept, region, level, headcount, sort_order) VALUES ('1890', 1, '1881', 'vijaya', 'qc', 'qc_07', 'NA', 'Director', 0, 101);
INSERT INTO org_members (id, org_id, parent_id, name, title, dept, region, level, headcount, sort_order) VALUES ('1891', 1, '1881', 'jerlin', 'qc', 'qc_07', 'NA', 'Director', 0, 102);
INSERT INTO org_members (id, org_id, parent_id, name, title, dept, region, level, headcount, sort_order) VALUES ('1906', 1, '1767', 'Saravanan', 'QA', 'Q_1', 'NA', 'VP', 1, 103);
INSERT INTO org_members (id, org_id, parent_id, name, title, dept, region, level, headcount, sort_order) VALUES ('1908', 1, '1906', 'sarath', 'Staff', 'General', 'NA', 'Director', 0, 104);
INSERT INTO org_members (id, org_id, parent_id, name, title, dept, region, level, headcount, sort_order) VALUES ('1909', 1, '1799', 'Name', 'Staff', 'General', 'NA', 'Director', 0, 105);
INSERT INTO org_members (id, org_id, parent_id, name, title, dept, region, level, headcount, sort_order) VALUES ('1928', 1, '1662', 'Saran', 'Staff', 'General', 'NA', 'Lead', 0, 106);
INSERT INTO org_members (id, org_id, parent_id, name, title, dept, region, level, headcount, sort_order) VALUES ('1929', 1, '1662', 'Sach', 'Staff', 'General', 'NA', 'Lead', 0, 107);
INSERT INTO org_members (id, org_id, parent_id, name, title, dept, region, level, headcount, sort_order) VALUES ('1930', 1, '1662', 'Jack1', 'Staff', 'General', 'NA', 'Lead', 0, 108);
INSERT INTO org_members (id, org_id, parent_id, name, title, dept, region, level, headcount, sort_order) VALUES ('1931', 1, '1662', 'Jack', 'Staff', 'General', 'NA', 'Lead', 0, 109);
INSERT INTO org_members (id, org_id, parent_id, name, title, dept, region, level, headcount, sort_order) VALUES ('1932', 1, '1662', 'Jerry1', 'Staff', 'General', 'NA', 'Lead', 0, 110);
INSERT INTO org_members (id, org_id, parent_id, name, title, dept, region, level, headcount, sort_order) VALUES ('1933', 1, '1662', 'Laras', 'Staff', 'General', 'NA', 'Lead', 0, 111);
INSERT INTO org_members (id, org_id, parent_id, name, title, dept, region, level, headcount, sort_order) VALUES ('2065', 1, '0', 'Shakthi', 'qw', 'SH', 'NA', 'C', 0, 112);
INSERT INTO org_members (id, org_id, parent_id, name, title, dept, region, level, headcount, sort_order) VALUES ('2089', 1, '0', 'DHONI', 'drt', 'MS', 'NA', 'C', 0, 113);
INSERT INTO org_members (id, org_id, parent_id, name, title, dept, region, level, headcount, sort_order) VALUES ('2104', 1, '0', 'Sud', 'saran', 'SUD', 'NA', 'C', 0, 114);
INSERT INTO org_members (id, org_id, parent_id, name, title, dept, region, level, headcount, sort_order) VALUES ('2105', 1, '0', 'demo', 'l', 'demo', 'NA', 'C', 0, 115);

-- Total: 115 employees migrated
-- Done
