
-- =============================================================
-- Risk Register Migration: formulation_risk_details -> risks
-- Risks: 43
-- =============================================================


INSERT INTO risks (org_id, name, owner, inherent_likelihood, inherent_impact, residual_likelihood, residual_impact, description, mitigation) VALUES (1, 'ee', 'Halle Berry', 2, 2, 2, 2, 'Category: Financial; Status: Low; Score: 4', 'Category: Financial');
INSERT INTO risks (org_id, name, owner, inherent_likelihood, inherent_impact, residual_likelihood, residual_impact, description, mitigation) VALUES (1, 'nkjn', 'Halle Berry', 2, 2, 2, 2, 'Category: Business Continuity; Status: Low; Score: 4', 'Category: Business Continuity');
INSERT INTO risks (org_id, name, owner, inherent_likelihood, inherent_impact, residual_likelihood, residual_impact, description, mitigation) VALUES (1, 'vinoth', 'Jennifer Lawrence', 2, 2, 2, 2, 'Category: Business Continuity; Status: Low; Score: 4', 'Category: Business Continuity');
INSERT INTO risks (org_id, name, owner, inherent_likelihood, inherent_impact, residual_likelihood, residual_impact, description, mitigation) VALUES (1, 'newmarch', 'HEIDI', 1, 2, 1, 2, 'Category: Business Continuity; Status: Very Low; Score: 2', 'Category: Business Continuity');
INSERT INTO risks (org_id, name, owner, inherent_likelihood, inherent_impact, residual_likelihood, residual_impact, description, mitigation) VALUES (1, 'newonne', 'Joseph', 3, 2, 2, 2, 'Category: Business; Status: Tolerable; Score: 6', 'Category: Business');
INSERT INTO risks (org_id, name, owner, inherent_likelihood, inherent_impact, residual_likelihood, residual_impact, description, mitigation) VALUES (1, 'test risk', 'Halle Berry', 1, 1, 1, 1, 'Status: Very Low; Score: 1', '');
INSERT INTO risks (org_id, name, owner, inherent_likelihood, inherent_impact, residual_likelihood, residual_impact, description, mitigation) VALUES (1, 'Test21', 'Joseph', 1, 2, 1, 2, 'Category: Financial; Status: Very Low; Score: 2', 'Category: Financial');
INSERT INTO risks (org_id, name, owner, inherent_likelihood, inherent_impact, residual_likelihood, residual_impact, description, mitigation) VALUES (1, 'Test1', 'Joseph', 1, 2, 1, 2, 'Category: Financial; Status: Very Low; Score: 2', 'Category: Financial');
INSERT INTO risks (org_id, name, owner, inherent_likelihood, inherent_impact, residual_likelihood, residual_impact, description, mitigation) VALUES (1, 'risk', 'Halle Berry', 3, 2, 2, 2, 'Category: Business; Status: Tolerable; Score: 6', 'Category: Business');
INSERT INTO risks (org_id, name, owner, inherent_likelihood, inherent_impact, residual_likelihood, residual_impact, description, mitigation) VALUES (1, 'Test1', 'Halle Berry', 1, 2, 1, 2, 'Category: Financial; Status: Very Low; Score: 2', 'Category: Financial');
INSERT INTO risks (org_id, name, owner, inherent_likelihood, inherent_impact, residual_likelihood, residual_impact, description, mitigation) VALUES (1, 'Test1', 'Halle Berry', 1, 2, 1, 2, 'Category: Financial; Status: Very Low; Score: 2', 'Category: Financial');
INSERT INTO risks (org_id, name, owner, inherent_likelihood, inherent_impact, residual_likelihood, residual_impact, description, mitigation) VALUES (1, 'Liquidity Risk - 1', 'Hemsworth', 4, 2, 3, 2, 'Category: Financial; Status: Tolerable; Score: 8', 'Category: Financial');
INSERT INTO risks (org_id, name, owner, inherent_likelihood, inherent_impact, residual_likelihood, residual_impact, description, mitigation) VALUES (1, 'Legal Risk - 1', 'Hemsworth', 4, 2, 3, 2, 'Category: Financial; Status: Tolerable; Score: 8', 'Category: Financial');
INSERT INTO risks (org_id, name, owner, inherent_likelihood, inherent_impact, residual_likelihood, residual_impact, description, mitigation) VALUES (1, 'wsss', 'Hemsworth', 2, 2, 2, 2, 'Category: Governance; Status: Low; Score: 4', 'Category: Governance');
INSERT INTO risks (org_id, name, owner, inherent_likelihood, inherent_impact, residual_likelihood, residual_impact, description, mitigation) VALUES (1, 'new', 'Hemsworth', 3, 2, 2, 2, 'Category: Financial; Status: Tolerable; Score: 6', 'Category: Financial');
INSERT INTO risks (org_id, name, owner, inherent_likelihood, inherent_impact, residual_likelihood, residual_impact, description, mitigation) VALUES (1, 'xcx', 'Hemsworth', 3, 3, 2, 2, 'Status: Tolerable; Score: 9', '');
INSERT INTO risks (org_id, name, owner, inherent_likelihood, inherent_impact, residual_likelihood, residual_impact, description, mitigation) VALUES (1, 'hh', 'Hemsworth', 3, 3, 2, 2, 'Status: Tolerable; Score: 9', '');
INSERT INTO risks (org_id, name, owner, inherent_likelihood, inherent_impact, residual_likelihood, residual_impact, description, mitigation) VALUES (1, 'ss', 'Hemsworth', 4, 4, 3, 3, 'Status: Very High; Score: 16', '');
INSERT INTO risks (org_id, name, owner, inherent_likelihood, inherent_impact, residual_likelihood, residual_impact, description, mitigation) VALUES (1, 'Risk', 'Dhoni', 2, 1, 2, 1, 'Category: Business; Status: Very Low; Score: 2', 'Category: Business');
INSERT INTO risks (org_id, name, owner, inherent_likelihood, inherent_impact, residual_likelihood, residual_impact, description, mitigation) VALUES (1, 'Liquidity Risk - 1', 'Dhoni', 4, 2, 3, 2, 'Category: Financial; Status: Tolerable; Score: 8', 'Category: Financial');
INSERT INTO risks (org_id, name, owner, inherent_likelihood, inherent_impact, residual_likelihood, residual_impact, description, mitigation) VALUES (1, 'Legal Risk - 1', 'Dhoni', 4, 2, 3, 2, 'Category: Financial; Status: Tolerable; Score: 8', 'Category: Financial');
INSERT INTO risks (org_id, name, owner, inherent_likelihood, inherent_impact, residual_likelihood, residual_impact, description, mitigation) VALUES (1, 'Risk', 'Karthik', 2, 1, 2, 1, 'Category: Business; Status: Very Low; Score: 2', 'Category: Business');
INSERT INTO risks (org_id, name, owner, inherent_likelihood, inherent_impact, residual_likelihood, residual_impact, description, mitigation) VALUES (1, 'risk', 'Raina', 1, 3, 1, 2, 'Status: Low; Score: 3', '');
INSERT INTO risks (org_id, name, owner, inherent_likelihood, inherent_impact, residual_likelihood, residual_impact, description, mitigation) VALUES (1, 'Risk', 'Hailey', 3, 2, 2, 2, 'Category: Financial; Status: Tolerable; Score: 6', 'Category: Financial');
INSERT INTO risks (org_id, name, owner, inherent_likelihood, inherent_impact, residual_likelihood, residual_impact, description, mitigation) VALUES (1, 'Risk', 'Hailey', 1, 1, 1, 1, 'Category: Business; Status: Very Low; Score: 1', 'Category: Business');
INSERT INTO risks (org_id, name, owner, inherent_likelihood, inherent_impact, residual_likelihood, residual_impact, description, mitigation) VALUES (1, 'Liquidity Risk - 1', 'Hailey', 4, 2, 3, 2, 'Category: Financial; Status: Tolerable; Score: 8', 'Category: Financial');
INSERT INTO risks (org_id, name, owner, inherent_likelihood, inherent_impact, residual_likelihood, residual_impact, description, mitigation) VALUES (1, 'Legal Risk - 1', 'Hailey', 4, 2, 3, 2, 'Category: Financial; Status: Tolerable; Score: 8', 'Category: Financial');
INSERT INTO risks (org_id, name, owner, inherent_likelihood, inherent_impact, residual_likelihood, residual_impact, description, mitigation) VALUES (1, 'risk', 'Aire', 1, 1, 1, 1, 'Category: Business; Status: Very Low; Score: 1', 'Category: Business');
INSERT INTO risks (org_id, name, owner, inherent_likelihood, inherent_impact, residual_likelihood, residual_impact, description, mitigation) VALUES (1, 'risk', 'Aire', 1, 1, 1, 1, 'Category: Business; Status: Very Low; Score: 1', 'Category: Business');
INSERT INTO risks (org_id, name, owner, inherent_likelihood, inherent_impact, residual_likelihood, residual_impact, description, mitigation) VALUES (1, 'Market Risk', 'Rohan', 3, 4, 2, 3, 'Category: Business Continuity; Status: High; Score: 12', 'Category: Business Continuity');
INSERT INTO risks (org_id, name, owner, inherent_likelihood, inherent_impact, residual_likelihood, residual_impact, description, mitigation) VALUES (1, 'Market Risks', 'joseph', 3, 3, 2, 2, 'Category: Business; Status: Tolerable; Score: 9', 'Category: Business');
INSERT INTO risks (org_id, name, owner, inherent_likelihood, inherent_impact, residual_likelihood, residual_impact, description, mitigation) VALUES (1, 'Technology Risks', 'joseph', 3, 3, 2, 2, 'Category: Business Continuity; Status: Tolerable; Score: 9', 'Category: Business Continuity');
INSERT INTO risks (org_id, name, owner, inherent_likelihood, inherent_impact, residual_likelihood, residual_impact, description, mitigation) VALUES (1, 'Regulatory Risks', 'joseph', 3, 4, 2, 3, 'Status: High; Score: 12', '');
INSERT INTO risks (org_id, name, owner, inherent_likelihood, inherent_impact, residual_likelihood, residual_impact, description, mitigation) VALUES (1, 'Financial Risks', 'joseph', 3, 3, 2, 2, 'Status: Tolerable; Score: 9', '');
INSERT INTO risks (org_id, name, owner, inherent_likelihood, inherent_impact, residual_likelihood, residual_impact, description, mitigation) VALUES (1, 'Strategic Risks', 'joseph', 4, 4, 3, 3, 'Category: Business; Status: Very High; Score: 16', 'Category: Business');
INSERT INTO risks (org_id, name, owner, inherent_likelihood, inherent_impact, residual_likelihood, residual_impact, description, mitigation) VALUES (1, 'HR Risks - Chances fo Key Management team leaving', 'joseph', 3, 3, 2, 2, 'Status: Tolerable; Score: 9', '');
INSERT INTO risks (org_id, name, owner, inherent_likelihood, inherent_impact, residual_likelihood, residual_impact, description, mitigation) VALUES (1, 'testing', 'josh', 1, 1, 1, 1, 'Category: Business; Status: Very Low; Score: 1', 'Category: Business');
INSERT INTO risks (org_id, name, owner, inherent_likelihood, inherent_impact, residual_likelihood, residual_impact, description, mitigation) VALUES (1, 'risk', 'virat', 1, 1, 1, 1, 'Status: Very Low; Score: 1', '');
INSERT INTO risks (org_id, name, owner, inherent_likelihood, inherent_impact, residual_likelihood, residual_impact, description, mitigation) VALUES (1, 'risks', 'virat', 1, 1, 1, 1, 'Status: Very Low; Score: 1', '');
INSERT INTO risks (org_id, name, owner, inherent_likelihood, inherent_impact, residual_likelihood, residual_impact, description, mitigation) VALUES (1, 'rk', 'surya', 1, 1, 1, 1, 'Category: Business; Status: Very Low; Score: 1', 'Category: Business');
INSERT INTO risks (org_id, name, owner, inherent_likelihood, inherent_impact, residual_likelihood, residual_impact, description, mitigation) VALUES (1, 'rk', 'rahman', 1, 1, 1, 1, 'Status: Very Low; Score: 1', '');
INSERT INTO risks (org_id, name, owner, inherent_likelihood, inherent_impact, residual_likelihood, residual_impact, description, mitigation) VALUES (1, 'risk formulation', 'inox', 2, 2, 2, 2, 'Category: Business Continuity; Status: Low; Score: 4', 'Category: Business Continuity');
INSERT INTO risks (org_id, name, owner, inherent_likelihood, inherent_impact, residual_likelihood, residual_impact, description, mitigation) VALUES (1, 'wertyuio', 'josephs', 3, 2, 2, 2, 'Status: Tolerable; Score: 6', '');

-- Total: 43 risks migrated
-- Done
