
-- =============================================================
-- Scorecard Migration: formulation_score_card + formulation_kpi -> scorecards
-- Scorecard entries: 421
-- =============================================================


INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Financial', 'Financial Overview', 100, 75, 'new', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Customer', 'Customer Overview', 100, 75, 'new', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Financial', 'Internal Process Overview', 100, 75, 'new', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Learning & Growth', 'Learning & Growth Overview', 100, 75, 'new', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Financial', 'Financial Overview', 100, 75, 'dd', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Customer', 'Customer Overview', 100, 75, 'dd', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Financial', 'Internal Process Overview', 100, 75, 'dd', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Learning & Growth', 'Learning & Growth Overview', 100, 75, 'dd', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Financial', 'Financial Overview', 100, 75, 'ss', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Customer', 'Customer Overview', 100, 75, 'ss', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Financial', 'Internal Process Overview', 100, 75, 'ss', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Learning & Growth', 'Learning & Growth Overview', 100, 75, 'ss', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Financial', 'Financial Overview', 100, 75, 'test', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Customer', 'Customer Overview', 100, 75, 'test', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Financial', 'Internal Process Overview', 100, 75, 'test', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Learning & Growth', 'Learning & Growth Overview', 100, 75, 'test', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Financial', 'Financial Overview', 100, 75, 'test one', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Customer', 'Customer Overview', 100, 75, 'test one', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Financial', 'Internal Process Overview', 100, 75, 'test one', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Learning & Growth', 'Learning & Growth Overview', 100, 75, 'test one', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Financial', 'Financial Overview', 100, 75, 'ss', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Customer', 'Customer Overview', 100, 75, 'ss', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Financial', 'Internal Process Overview', 100, 75, 'ss', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Learning & Growth', 'Learning & Growth Overview', 100, 75, 'ss', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Financial', 'Financial Overview', 100, 75, 'new', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Customer', 'Customer Overview', 100, 75, 'new', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Financial', 'Internal Process Overview', 100, 75, 'new', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Learning & Growth', 'Learning & Growth Overview', 100, 75, 'new', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Financial', 'Financial Overview', 100, 75, 'rr', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Customer', 'Customer Overview', 100, 75, 'rr', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Financial', 'Internal Process Overview', 100, 75, 'rr', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Learning & Growth', 'Learning & Growth Overview', 100, 75, 'rr', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Financial', 'Financial Overview', 100, 75, 'ss', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Customer', 'Customer Overview', 100, 75, 'ss', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Financial', 'Internal Process Overview', 100, 75, 'ss', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Learning & Growth', 'Learning & Growth Overview', 100, 75, 'ss', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Financial', 'Financial Overview', 100, 75, 'ss', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Customer', 'Customer Overview', 100, 75, 'ss', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Financial', 'Internal Process Overview', 100, 75, 'ss', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Learning & Growth', 'Learning & Growth Overview', 100, 75, 'ss', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Financial', 'Financial Overview', 100, 75, 'ss', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Customer', 'Customer Overview', 100, 75, 'ss', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Financial', 'Internal Process Overview', 100, 75, 'ss', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Learning & Growth', 'Learning & Growth Overview', 100, 75, 'ss', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Financial', 'Financial Overview', 100, 75, 'new', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Customer', 'Customer Overview', 100, 75, 'new', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Financial', 'Internal Process Overview', 100, 75, 'new', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Learning & Growth', 'Learning & Growth Overview', 100, 75, 'new', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Financial', 'Financial Overview', 100, 75, 'sss', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Customer', 'Customer Overview', 100, 75, 'sss', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Financial', 'Internal Process Overview', 100, 75, 'sss', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Learning & Growth', 'Learning & Growth Overview', 100, 75, 'sss', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Financial', 'Environmental Overview', 100, 75, 'ESG', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Financial', 'Social Overview', 100, 75, 'ESG', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Financial', 'Governance Overview', 100, 75, 'ESG', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Financial', 'Sustainability Overview', 100, 75, 'ESG', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Financial', 'Financial Overview', 100, 75, 'ss', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Customer', 'Customer Overview', 100, 75, 'ss', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Financial', 'Internal Process Overview', 100, 75, 'ss', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Learning & Growth', 'Learning & Growth Overview', 100, 75, 'ss', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Financial', 'Financial Overview', 100, 75, 'new', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Customer', 'Customer Overview', 100, 75, 'new', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Financial', 'Internal Process Overview', 100, 75, 'new', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Learning & Growth', 'Learning & Growth Overview', 100, 75, 'new', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Financial', 'Financial Overview', 100, 75, 'neww', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Customer', 'Customer Overview', 100, 75, 'neww', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Financial', 'Internal Process Overview', 100, 75, 'neww', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Learning & Growth', 'Learning & Growth Overview', 100, 75, 'neww', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Financial', 'Financial Overview', 100, 75, 'new', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Customer', 'Customer Overview', 100, 75, 'new', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Financial', 'Internal Process Overview', 100, 75, 'new', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Learning & Growth', 'Learning & Growth Overview', 100, 75, 'new', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Financial', 'Financial Overview', 100, 75, 'Strategy', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Customer', 'Customer Overview', 100, 75, 'Strategy', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Financial', 'Internal Process Overview', 100, 75, 'Strategy', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Learning & Growth', 'Learning & Growth Overview', 100, 75, 'Strategy', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Financial', 'Financial Overview', 100, 75, 'Strategy Formulation', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Customer', 'Customer Overview', 100, 75, 'Strategy Formulation', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Financial', 'Internal Process Overview', 100, 75, 'Strategy Formulation', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Learning & Growth', 'Learning & Growth Overview', 100, 75, 'Strategy Formulation', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Financial', 'Financial Overview', 100, 75, 'Strategy Formulation', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Customer', 'Customer Overview', 100, 75, 'Strategy Formulation', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Financial', 'Internal Process Overview', 100, 75, 'Strategy Formulation', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Learning & Growth', 'Learning & Growth Overview', 100, 75, 'Strategy Formulation', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Financial', 'Financial Overview', 100, 75, 'teet1', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Customer', 'Customer Overview', 100, 75, 'teet1', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Financial', 'Internal Process Overview', 100, 75, 'teet1', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Learning & Growth', 'Learning & Growth Overview', 100, 75, 'teet1', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Financial', 'Financial Overview', 100, 75, 'teet1', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Customer', 'Customer Overview', 100, 75, 'teet1', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Financial', 'Internal Process Overview', 100, 75, 'teet1', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Learning & Growth', 'Learning & Growth Overview', 100, 75, 'teet1', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Financial', 'Financial Overview', 100, 75, 'ss', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Customer', 'Customer Overview', 100, 75, 'ss', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Financial', 'Internal Process Overview', 100, 75, 'ss', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Learning & Growth', 'Learning & Growth Overview', 100, 75, 'ss', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Financial', 'Financial Overview', 100, 75, 'formulation', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Customer', 'Customer Overview', 100, 75, 'formulation', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Financial', 'Internal Process Overview', 100, 75, 'formulation', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Learning & Growth', 'Learning & Growth Overview', 100, 75, 'formulation', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Financial', 'Financials Overview', 100, 75, 'Sample Strategy', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Customer', 'Customer Overview', 100, 75, 'Sample Strategy', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Financial', 'Internal Process Overview', 100, 75, 'Sample Strategy', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Learning & Growth', 'Learning & Growth Overview', 100, 75, 'Sample Strategy', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Financial', 'Financial Overview', 100, 75, 'Strategic Plan LHDA', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Customer', 'Customer Overview', 100, 75, 'Strategic Plan LHDA', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Financial', 'Internal Process Overview', 100, 75, 'Strategic Plan LHDA', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Financial', 'ANCILLARY DEVELOPMENTS Overview', 100, 75, 'Strategic Plan LHDA', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Financial', 'Cyber Security  Overview', 100, 75, 'IT Risk', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Customer', 'Customer Overview', 100, 75, 'IT Risk', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Financial', 'Internal Process Overview', 100, 75, 'IT Risk', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Learning & Growth', 'Learning & Growth Overview', 100, 75, 'IT Risk', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Financial', 'Strategic Risks Overview', 100, 75, 'ERM Business Risk', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Financial', 'People & Reputation Overview', 100, 75, 'ERM Business Risk', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Financial', 'Internal Process Overview', 100, 75, 'ERM Business Risk', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Financial', 'Legal & Regulatory Risks Overview', 100, 75, 'ERM Business Risk', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Financial', 'Brand Recognition Overview', 100, 75, 'Digital Marketing', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Customer', 'Customer Overview', 100, 75, 'Digital Marketing', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Financial', 'Internal Process Overview', 100, 75, 'Digital Marketing', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Learning & Growth', 'Learning & Growth Overview', 100, 75, 'Digital Marketing', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Financial', 'Financial Overview', 100, 75, 'TestingFormulation', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Customer', 'Customer Overview', 100, 75, 'TestingFormulation', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Financial', 'Internal Process Overview', 100, 75, 'TestingFormulation', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Learning & Growth', 'Learning & Growth Overview', 100, 75, 'TestingFormulation', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Financial', 'Financial Overview', 100, 75, 'new', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Customer', 'Customer Overview', 100, 75, 'new', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Financial', 'Internal Process Overview', 100, 75, 'new', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Learning & Growth', 'Learning & Growth Overview', 100, 75, 'new', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Financial', 'DEVELOPMENT AND MANAGEMENT OF INTRASTRUCTURE Overview', 100, 75, 'nrww', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Customer', 'Customer Overview', 100, 75, 'nrww', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Financial', 'Internal Process Overview', 100, 75, 'nrww', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Learning & Growth', 'Learning & Growth Overview', 100, 75, 'nrww', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Financial', 'Financial Overview', 100, 75, 'Scorecard new strategy', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Customer', 'Customer Overview', 100, 75, 'Scorecard new strategy', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Financial', 'Internal Process Overview', 100, 75, 'Scorecard new strategy', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Learning & Growth', 'Learning & Growth Overview', 100, 75, 'Scorecard new strategy', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Financial', 'Financial Overview', 100, 75, 'Strategic Risk', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Customer', 'Customer Overview', 100, 75, 'Strategic Risk', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Financial', 'Internal Process Overview', 100, 75, 'Strategic Risk', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Learning & Growth', 'Learning & Growth Overview', 100, 75, 'Strategic Risk', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Financial', 'Financial Overview', 100, 75, 'Regulatory Risk', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Customer', 'Customer Overview', 100, 75, 'Regulatory Risk', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Financial', 'Internal Process Overview', 100, 75, 'Regulatory Risk', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Learning & Growth', 'Learning & Growth Overview', 100, 75, 'Regulatory Risk', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Financial', 'Financial Overview', 100, 75, 'niranjan', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Customer', 'Customer Overview', 100, 75, 'niranjan', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Financial', 'Internal Process Overview', 100, 75, 'niranjan', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Learning & Growth', 'Learning & Growth Overview', 100, 75, 'niranjan', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Financial', 'Financial Overview', 100, 75, 'formul', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Customer', 'Customer Overview', 100, 75, 'formul', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Financial', 'Internal Process Overview', 100, 75, 'formul', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Learning & Growth', 'Learning & Growth Overview', 100, 75, 'formul', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Financial', 'Financial Overview', 100, 75, 'nithya', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Customer', 'Customer Overview', 100, 75, 'nithya', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Financial', 'Internal Process Overview', 100, 75, 'nithya', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Learning & Growth', 'Learning & Growth Overview', 100, 75, 'nithya', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Financial', 'Financial Overview', 100, 75, 'otto', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Customer', 'Customer Overview', 100, 75, 'otto', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Financial', 'Internal Process Overview', 100, 75, 'otto', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Learning & Growth', 'Learning & Growth Overview', 100, 75, 'otto', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Financial', 'Financial Overview', 100, 75, 'Formulation', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Customer', 'Customer Overview', 100, 75, 'Formulation', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Financial', 'Internal Process Overview', 100, 75, 'Formulation', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Learning & Growth', 'Learning & Growth Overview', 100, 75, 'Formulation', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Financial', 'Financial Overview', 100, 75, 'Scorecard new strategy', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Customer', 'Customer Overview', 100, 75, 'Scorecard new strategy', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Financial', 'Internal Process Overview', 100, 75, 'Scorecard new strategy', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Learning & Growth', 'Learning & Growth Overview', 100, 75, 'Scorecard new strategy', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Financial', 'Financial Overview', 100, 75, 'performance', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Customer', 'Customer Overview', 100, 75, 'performance', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Financial', 'Internal Process Overview', 100, 75, 'performance', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Learning & Growth', 'Learning & Growth Overview', 100, 75, 'performance', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Financial', 'Financial Overview', 100, 75, 'ss', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Customer', 'Customer Overview', 100, 75, 'ss', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Financial', 'Internal Process Overview', 100, 75, 'ss', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Learning & Growth', 'Learning & Growth Overview', 100, 75, 'ss', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Financial', 'Financial Overview', 100, 75, 'new', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Customer', 'Customer Overview', 100, 75, 'new', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Financial', 'Internal Process Overview', 100, 75, 'new', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Learning & Growth', 'Learning & Growth Overview', 100, 75, 'new', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Financial', 'Financial Overview', 100, 75, 'Strategy Formulation', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Customer', 'Customer Overview', 100, 75, 'Strategy Formulation', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Financial', 'Internal Process Overview', 100, 75, 'Strategy Formulation', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Learning & Growth', 'Learning & Growth Overview', 100, 75, 'Strategy Formulation', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Financial', 'Financial Overview', 100, 75, 'Scorecard new strategy', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Customer', 'Customer Overview', 100, 75, 'Scorecard new strategy', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Financial', 'Internal Process Overview', 100, 75, 'Scorecard new strategy', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Learning & Growth', 'Learning & Growth Overview', 100, 75, 'Scorecard new strategy', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Financial', 'Financial Overview', 100, 75, 'new', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Customer', 'Customer Overview', 100, 75, 'new', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Financial', 'Internal Process Overview', 100, 75, 'new', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Learning & Growth', 'Learning & Growth Overview', 100, 75, 'new', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Financial', 'Financial Overview', 100, 75, 'Sf', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Customer', 'Customer Overview', 100, 75, 'Sf', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Financial', 'Internal Process Overview', 100, 75, 'Sf', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Learning & Growth', 'Learning & Growth Overview', 100, 75, 'Sf', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Financial', 'Financial Overview', 100, 75, 'jaggy', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Customer', 'Customer Overview', 100, 75, 'jaggy', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Financial', 'Internal Process Overview', 100, 75, 'jaggy', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Learning & Growth', 'Learning & Growth Overview', 100, 75, 'jaggy', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Financial', 'Financial Overview', 100, 75, 'Strategy', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Customer', 'Customer Overview', 100, 75, 'Strategy', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Financial', 'Internal Process Overview', 100, 75, 'Strategy', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Learning & Growth', 'Learning & Growth Overview', 100, 75, 'Strategy', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Financial', 'Financial Overview', 100, 75, 'ss', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Customer', 'Customer Overview', 100, 75, 'ss', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Financial', 'Internal Process Overview', 100, 75, 'ss', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Learning & Growth', 'Learning & Growth Overview', 100, 75, 'ss', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Financial', 'Financial Overview', 100, 75, 'scr', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Customer', 'Customer Overview', 100, 75, 'scr', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Financial', 'Internal Process Overview', 100, 75, 'scr', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Learning & Growth', 'Learning & Growth Overview', 100, 75, 'scr', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Financial', 'Financials Overview', 100, 75, 'super', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Financial', 'Customers Overview', 100, 75, 'super', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Financial', 'Internal Process Overview', 100, 75, 'super', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Learning & Growth', 'Learning & Growth Overview', 100, 75, 'super', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Financial', 'Financial Overview', 100, 75, 'sf', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Customer', 'Customer Overview', 100, 75, 'sf', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Financial', 'Internal Process Overview', 100, 75, 'sf', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Learning & Growth', 'Learning & Growth Overview', 100, 75, 'sf', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Financial', 'Financial Overview', 100, 75, 'sf', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Customer', 'Customer Overview', 100, 75, 'sf', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Financial', 'Internal Process Overview', 100, 75, 'sf', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Learning & Growth', 'Learning & Growth Overview', 100, 75, 'sf', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Financial', 'Financial Overview', 100, 75, 'Scorecard', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Customer', 'Customer Overview', 100, 75, 'Scorecard', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Financial', 'Internal Process Overview', 100, 75, 'Scorecard', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Learning & Growth', 'Learning & Growth Overview', 100, 75, 'Scorecard', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Financial', 'Financial Overview', 100, 75, 'Scorecard', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Customer', 'Customer Overview', 100, 75, 'Scorecard', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Financial', 'Internal Process Overview', 100, 75, 'Scorecard', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Learning & Growth', 'Learning & Growth Overview', 100, 75, 'Scorecard', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Financial', 'Financial Overview', 100, 75, 'Scorecard', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Customer', 'Customer Overview', 100, 75, 'Scorecard', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Financial', 'Internal Process Overview', 100, 75, 'Scorecard', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Learning & Growth', 'Learning & Growth Overview', 100, 75, 'Scorecard', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Financial', 'Financial Overview', 100, 75, 'Strategy formulation', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Customer', 'Customer Overview', 100, 75, 'Strategy formulation', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Financial', 'Internal Process Overview', 100, 75, 'Strategy formulation', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Learning & Growth', 'Learning & Growth Overview', 100, 75, 'Strategy formulation', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Financial', 'Financial Overview', 100, 75, 'st for', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Customer', 'Customer Overview', 100, 75, 'st for', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Financial', 'Internal Process Overview', 100, 75, 'st for', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Learning & Growth', 'Learning & Growth Overview', 100, 75, 'st for', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Financial', 'Financial Overview', 100, 75, 'New Test', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Customer', 'Customer Overview', 100, 75, 'New Test', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Financial', 'Internal Process Overview', 100, 75, 'New Test', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Learning & Growth', 'Learning & Growth Overview', 100, 75, 'New Test', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Financial', 'Financial Overview', 100, 75, 'New Test', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Customer', 'Customer Overview', 100, 75, 'New Test', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Financial', 'Internal Process Overview', 100, 75, 'New Test', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Learning & Growth', 'Learning & Growth Overview', 100, 75, 'New Test', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Financial', 'Financial Overview', 100, 75, 'New Test', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Customer', 'Customer Overview', 100, 75, 'New Test', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Financial', 'Internal Process Overview', 100, 75, 'New Test', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Learning & Growth', 'Learning & Growth Overview', 100, 75, 'New Test', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Financial', 'Financial Overview', 100, 75, 'Test04', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Customer', 'Customer Overview', 100, 75, 'Test04', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Financial', 'Internal Process Overview', 100, 75, 'Test04', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Learning & Growth', 'Learning & Growth Overview', 100, 75, 'Test04', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Financial', 'Financial Overview', 100, 75, 'Test-05', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Customer', 'Customer Overview', 100, 75, 'Test-05', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Financial', 'Internal Process Overview', 100, 75, 'Test-05', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Learning & Growth', 'Learning & Growth Overview', 100, 75, 'Test-05', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Financial', 'Financial Overview', 100, 75, 'Test04', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Customer', 'Customer Overview', 100, 75, 'Test04', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Financial', 'Internal Process Overview', 100, 75, 'Test04', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Learning & Growth', 'Learning & Growth Overview', 100, 75, 'Test04', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Financial', 'Financial Overview', 100, 75, 'Test-05', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Customer', 'Customer Overview', 100, 75, 'Test-05', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Financial', 'Internal Process Overview', 100, 75, 'Test-05', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Learning & Growth', 'Learning & Growth Overview', 100, 75, 'Test-05', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Financial', 'Financial Overview', 100, 75, 'Str01', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Customer', 'Customer Overview', 100, 75, 'Str01', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Financial', 'Internal Process Overview', 100, 75, 'Str01', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Learning & Growth', 'Learning & Growth Overview', 100, 75, 'Str01', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Financial', 'Financial Overview', 100, 75, 'Corporate - Strategy Plan', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Customer', 'Customer Overview', 100, 75, 'Corporate - Strategy Plan', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Financial', 'Internal Process Overview', 100, 75, 'Corporate - Strategy Plan', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Learning & Growth', 'Learning & Growth Overview', 100, 75, 'Corporate - Strategy Plan', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Financial', 'Financial Overview', 100, 75, 'Strategy Team', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Customer', 'Customer Overview', 100, 75, 'Strategy Team', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Financial', 'Internal Process Overview', 100, 75, 'Strategy Team', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Learning & Growth', 'Learning & Growth Overview', 100, 75, 'Strategy Team', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Financial', 'Financial Overview', 100, 75, 'Strategy Team', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Customer', 'Customer Overview', 100, 75, 'Strategy Team', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Financial', 'Internal Process Overview', 100, 75, 'Strategy Team', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Learning & Growth', 'Learning & Growth Overview', 100, 75, 'Strategy Team', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Financial', 'Financial Overview', 100, 75, 'Strategy Team', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Customer', 'Customer Overview', 100, 75, 'Strategy Team', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Financial', 'Internal Process Overview', 100, 75, 'Strategy Team', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Learning & Growth', 'Learning & Growth Overview', 100, 75, 'Strategy Team', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Financial', 'Financial Overview', 100, 75, 'Strategy Team', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Customer', 'Customer Overview', 100, 75, 'Strategy Team', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Financial', 'Internal Process Overview', 100, 75, 'Strategy Team', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Learning & Growth', 'Learning & Growth Overview', 100, 75, 'Strategy Team', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Financial', 'Operations  Overview', 100, 75, 'Strategy Team', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Financial', 'ESG Overview', 100, 75, 'Strategy Team', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Financial', 'Policy & Regulatory Leadership Overview', 100, 75, '85', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Financial', 'Local Government Capability & Capacity Building Overview', 100, 75, '85', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Financial', 'Customer & Community Service Excellence Overview', 100, 75, '85', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Financial', 'Risk, Performance & Integrity Oversight Overview', 100, 75, '85', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Financial', 'Policy Development & Regulatory Management Overview', 100, 75, '86', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Financial', 'Local Government Capacity Development Overview', 100, 75, '86', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Financial', 'Program & Grant Administration Overview', 100, 75, '86', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Financial', 'Monitoring, Compliance & Performance Oversight Overview', 100, 75, '86', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Financial', 'Effective Management of Government Funding Programs Overview', 100, 75, '87', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Financial', 'Financial Sustainability of Local Councils Overview', 100, 75, '87', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Financial', 'Financial Governance and Compliance Oversight Overview', 100, 75, '87', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Financial', 'Resource Planning and Financial Management of OLG Overview', 100, 75, '87', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Financial', 'GRC Overview', 100, 75, '88', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Financial', 'Customer First Overview', 100, 75, '88', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Financial', 'People First Overview', 100, 75, '88', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Financial', 'Sustainable Profitable Growth Overview', 100, 75, '88', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Financial', 'GRC Overview', 100, 75, '89', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Financial', 'Customer First Overview', 100, 75, '89', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Financial', 'People First Overview', 100, 75, '89', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Financial', 'Sustainable Profitable Growth Overview', 100, 75, '89', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Financial', 'GRC Overview', 100, 75, '90', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Financial', 'Customer First Overview', 100, 75, '90', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Financial', 'People First Overview', 100, 75, '90', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Financial', 'Sustainable Profitable Growth Overview', 100, 75, '90', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Financial', 'GRC Overview', 100, 75, '91', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Financial', 'Customer First Overview', 100, 75, '91', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Financial', 'People First Overview', 100, 75, '91', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Financial', 'Sustainable Profitable Growth Overview', 100, 75, '91', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Financial', 'Technology Overview', 100, 75, '88', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Financial', 'Technology Overview', 100, 75, '90', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Financial', 'Technology Overview', 100, 75, 'Leadership Strategy', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Financial', 'Technology Overview', 100, 75, 'Branch Strategy', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Financial', 'Organizational Capability & Operational Excellence Overview', 100, 75, 'RD Corporate Strategic Plan', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Financial', 'Stakeholder Collaboration & Government Alignment Overview', 100, 75, 'RD Corporate Strategic Plan', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Financial', 'Stakeholder Engagement & Sector Coordination Overview', 100, 75, 'NSW Operational Strategy', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Financial', 'Regulatory Governance Overview', 100, 75, '92', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Financial', 'Performance & Compliance Oversight Overview', 100, 75, '92', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Financial', 'Risk Management & Early Intervention Overview', 100, 75, '92', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Financial', 'Sector Integrity & Accountability Overview', 100, 75, '92', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Financial', 'Intergovernmental Governance & Collaboration Overview', 100, 75, 'NSW Governance Strategy', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Financial', 'Legislative & Regulatory Compliance Overview', 100, 75, '93', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Financial', 'Performance & Operational Compliance Overview', 100, 75, '93', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Financial', 'Governance Compliance Overview', 100, 75, '93', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Financial', 'Risk & Integrity Compliance Overview', 100, 75, '93', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Financial', 'Regulatory Enforcement & Corrective Action Overview', 100, 75, 'NSW Compliance Strategy', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Financial', 'testkpi', 50.0, 40.0, 'KPI Owner', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Customer', 'KPi - Objective - Fin1', 20.0, 16.0, 'KPI Owner', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Internal Processes', 'FIN_obj1_kpi1', 100.0, 80.0, 'KPI Owner', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Learning & Growth', 'FIN_obj1_kpi1', 100.0, 80.0, 'KPI Owner', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Financial', 'FIN_obj1_kpi1', 100.0, 80.0, 'KPI Owner', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Customer', 'FIN_obj1_kpi1', 100.0, 80.0, 'KPI Owner', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Internal Processes', 'FIN_obj1_kpi1', 100.0, 80.0, 'KPI Owner', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Learning & Growth', 'dd', 33.0, 26.400000000000002, 'KPI Owner', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Financial', 'ne', 55.0, 44.0, 'KPI Owner', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Customer', 'vss', 44.0, 35.2, 'KPI Owner', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Internal Processes', 'Carbon FootPrint KPI 1', 100.0, 80.0, 'KPI Owner', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Learning & Growth', 'gg', 55.0, 44.0, 'KPI Owner', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Financial', 'kpi', 90.0, 72.0, 'KPI Owner', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Customer', 'customer kpi', 90.0, 72.0, 'KPI Owner', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Internal Processes', 'kpi', 90.0, 72.0, 'KPI Owner', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Learning & Growth', 'kpi', 100.0, 80.0, 'KPI Owner', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Financial', 'kpi', 70.0, 56.0, 'KPI Owner', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Customer', 'kpi
', 100.0, 80.0, 'KPI Owner', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Internal Processes', 'kpi', 100.0, 80.0, 'KPI Owner', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Learning & Growth', 'kpi', 100.0, 80.0, 'KPI Owner', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Financial', 'kpi', 100.0, 80.0, 'KPI Owner', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Customer', 'kpi', 100.0, 80.0, 'KPI Owner', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Internal Processes', 'kpi', 100.0, 80.0, 'KPI Owner', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Learning & Growth', 'kpi', 100.0, 80.0, 'KPI Owner', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Financial', 'kpi', 89.0, 71.2, 'KPI Owner', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Customer', 'Obj1 KPI1', 2000.0, 1600.0, 'KPI Owner', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Internal Processes', 'Fin Obj1 KPI1', 1000.0, 800.0, 'KPI Owner', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Learning & Growth', 'Periodic and Timely Reportings', 566.0, 452.8, 'KPI Owner', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Financial', 'Consolidation of # of Mid-Year Reports', 400.0, 320.0, 'KPI Owner', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Customer', '# of Risk Audit Reports Submitted to the Board', 18.0, 14.4, 'KPI Owner', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Internal Processes', 'news', 400.0, 320.0, 'KPI Owner', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Learning & Growth', 'New Visitor on Website', 100.0, 80.0, 'KPI Owner', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Financial', 'tset2', 500.0, 400.0, 'KPI Owner', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Customer', 'newws', 600.0, 480.0, 'KPI Owner', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Internal Processes', 'new ventures operational', 144.0, 115.2, 'KPI Owner', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Learning & Growth', 'new1test', 400.0, 320.0, 'KPI Owner', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Financial', 'rose', 30000.0, 24000.0, 'KPI Owner', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Customer', 'sirenn', 40000.0, 32000.0, 'KPI Owner', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Internal Processes', 'jessi', 30000.0, 24000.0, 'KPI Owner', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Learning & Growth', 'trans', 50000.0, 40000.0, 'KPI Owner', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Financial', 'jess', 100000.0, 80000.0, 'KPI Owner', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Customer', 'tron', 50000.0, 40000.0, 'KPI Owner', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Internal Processes', 'dracks', 150000.0, 120000.0, 'KPI Owner', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Learning & Growth', 'punitha', 70000.0, 56000.0, 'KPI Owner', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Financial', 'narayanan', 100000.0, 80000.0, 'KPI Owner', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Customer', 'baby', 40000.0, 32000.0, 'KPI Owner', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Internal Processes', 'joy', 50000.0, 40000.0, 'KPI Owner', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Learning & Growth', 'kpi', 100.0, 80.0, 'KPI Owner', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Financial', 'new1test', 400.0, 320.0, 'KPI Owner', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Customer', 'kpi performance', 150.0, 120.0, 'KPI Owner', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Internal Processes', 'kpi indicator1', 400.0, 320.0, 'KPI Owner', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Learning & Growth', 'ss', 566.0, 452.8, 'KPI Owner', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Financial', 'kpifere', 555.0, 444.0, 'KPI Owner', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Customer', 'new1test', 400.0, 320.0, 'KPI Owner', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Internal Processes', 'finnce', 98.0, 78.4, 'KPI Owner', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Learning & Growth', 'fin', 99.0, 79.2, 'KPI Owner', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Financial', 'score', 100.0, 80.0, 'KPI Owner', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Customer', 'kpi', 90.0, 72.0, 'KPI Owner', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Internal Processes', 'KPI 2', 100.0, 80.0, 'KPI Owner', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Learning & Growth', 'KPI 2', 100.0, 80.0, 'KPI Owner', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Financial', 'KPI', 100.0, 80.0, 'KPI Owner', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Customer', 'KPI', 100.0, 80.0, 'KPI Owner', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Internal Processes', 'KPI new', 100.0, 80.0, 'KPI Owner', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Learning & Growth', 'Kpi Test', 100.0, 80.0, 'KPI Owner', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Financial', 'Kpi Test', 100.0, 80.0, 'KPI Owner', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Customer', 'TEst02', 10.0, 8.0, 'KPI Owner', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Internal Processes', 'Test-03', 100.0, 80.0, 'KPI Owner', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Learning & Growth', 'kpi02', 10.0, 8.0, 'KPI Owner', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Financial', 'Kpi01', 10.0, 8.0, 'KPI Owner', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Customer', 'Sales', 100000.0, 80000.0, 'KPI Owner', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Internal Processes', 'Number of feasibility and economical studies conducted', 5.0, 4.0, 'KPI Owner', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Learning & Growth', 'Test002', 200.0, 160.0, 'KPI Owner', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Financial', 'Number Of Projects Designed', 12.0, 9.600000000000001, 'KPI Owner', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Customer', 'Number Of Kilometres Constructed_Upgraded_Rehabilitated', 1800.0, 1440.0, 'KPI Owner', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Internal Processes', 'Increased Sources Of Funding', 7.0, 5.6000000000000005, 'KPI Owner', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Learning & Growth', 'Increase In Earned Revenue Ratio', 35.0, 28.0, 'KPI Owner', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Financial', 'Number Of Policies_Procedures And Processes Developed And Reviewed Annually', 8.0, 6.4, 'KPI Owner', 'on-track');
INSERT INTO scorecards (org_id, perspective, kpi_name, target, actual, owner, status) VALUES (1, 'Customer', 'Number Business Process Maps Developed ', 8.0, 6.4, 'KPI Owner', 'on-track');

-- Total: 421 scorecard entries migrated
-- Done
